import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { HomeIntro } from '@/components/home/intro';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="background.100">
        <HomeIntro />
      </Box>
    </>
  );
}
